sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
before_install:
  - npm i -g npm@^2.0.0
  - npm i -g hexo-cli
before_script:
  - npm prune
script:
  - git config --global user.email "abalone0204@gmail.com"
  - git config --global user.name "abalone0204"
  - npm run deploy
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
